In [2]:
import numpy as np

In [35]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#### 1. How many negative numbers are there?

In [9]:
len(a[a < 0])

4

#### 2. How many positive numbers are there?

In [80]:
len(a[a >= 0])

8

#### 3. How many even positive numbers are there?

In [12]:
len(a[(a > 0) & (a % 2 == 0)])

3

#### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [17]:
len((a + 3)[(a + 3) > 0])

10

#### 5. If you squared each number, what would the new mean and standard deviation be?

In [21]:
a2 = a ** 2

In [24]:
a2.std()

144.0243035046516

In [25]:
a2.mean()

74.0

#### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [27]:
a.mean()

3.0

In [28]:
a - (a.mean())

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [29]:
(a - (a.mean())).mean()

0.0

#### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [32]:
(a - (a.mean())) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# Bonus
#### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

#### Setup 1

In [46]:
## Setup 1
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Use python's built in functionality/operators to determine the following:

In [51]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_b = sum(b)
sum_of_b

55

In [54]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_b = min(b)
min_of_b

1

In [56]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_b = max(b)
max_of_b

10

In [61]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_b = sum_of_b / len(b)
sum_of_b / len(b)

5.5

In [71]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_b = 1
for i in b:
    product_of_b *= i
print(product_of_b)


3628800


In [72]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_b = []
for i in b:
    squares_of_b.append(i ** 2)
print(squares_of_b)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [78]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_b = []
for i in b:
    if i % 2 != 0:
        odds_in_b.append(i)
print(odds_in_b)

[1, 3, 5, 7, 9]


In [79]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_b = []
for i in b:
    if i % 2 == 0:
        evens_in_b.append(i)
print(evens_in_b)

[2, 4, 6, 8, 10]


#### Setup 2

In [82]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
c = [
    [3, 4, 5],
    [6, 7, 8]
]
c = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [94]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_c = c.sum()
sum_of_c

33

In [95]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_c = min(c[0]) if min(c[0]) <= min(c[1]) else min(c[1]) 
min_of_c = c.min()
min_of_c

3

In [96]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_c = c.max()
max_of_c

8

In [97]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_c = c.mean()
mean_of_c

5.5

In [103]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

product_of_c = np.prod(c)
product_of_c

20160

In [105]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_c = np.square(c)
squares_of_c

array([[ 9, 16, 25],
       [36, 49, 64]])

In [107]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

c[c % 2 == 1]

array([3, 5, 7])

In [108]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

c[c % 2 == 0]

array([4, 6, 8])

In [109]:
# Exercise 9 - print out the shape of the array b.

print(c.shape)

(2, 3)


In [110]:
# Exercise 10 - transpose the array b.
np.transpose(c)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [112]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(c,(1,6))

array([[3, 4, 5, 6, 7, 8]])

In [113]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(c,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

#### Setup 3

In [135]:
## Setup 3
d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [125]:
# Exercise 1 - Find the min, max, sum, and product of c.
d.min(), d.max(), d.sum(), d.prod()

(1, 9, 45, 362880)

In [120]:
# Exercise 2 - Determine the standard deviation of c.
d.std()

2.581988897471611

In [122]:
# Exercise 3 - Determine the variance of c.
d.var()

6.666666666666667

In [127]:
# Exercise 4 - Print out the shape of the array c
print(d.shape)

(3, 3)


In [128]:
# Exercise 5 - Transpose c and print out transposed result.
d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [132]:
# Exercise 6 - Get the dot product of the array c with c. 
d.dot(d,d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [139]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(d * d.transpose()).sum()

261

In [141]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
(d * d.transpose()).prod()

131681894400

#### Setup 4

In [143]:
e = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
e = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [151]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(np.radians(e))

array([[ 1.00000000e+00,  5.00000000e-01,  7.07106781e-01,
         0.00000000e+00,  8.66025404e-01,  1.22464680e-16],
       [ 7.07106781e-01, -1.00000000e+00, -5.00000000e-01,
        -1.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 8.66025404e-01,  7.07106781e-01, -7.07106781e-01,
         1.00000000e+00, -7.07106781e-01,  1.22464680e-16]])

In [152]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(np.radians(e))

array([[ 6.12323400e-17,  8.66025404e-01,  7.07106781e-01,
         1.00000000e+00, -5.00000000e-01, -1.00000000e+00],
       [ 7.07106781e-01,  6.12323400e-17,  8.66025404e-01,
        -1.83697020e-16,  6.12323400e-17,  1.00000000e+00],
       [ 5.00000000e-01,  7.07106781e-01,  7.07106781e-01,
         6.12323400e-17,  7.07106781e-01, -1.00000000e+00]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d


In [ ]:
# Exercise 4 - Find all the negative numbers in d


In [ ]:
# Exercise 5 - Find all the positive numbers in d
